Rapid Share (Without Gems)/config/routes.rb
Rails.application.routes.draw do
  root :to => 'documents#index'

  resources :documents
  resources :users, :only => [:index, :destroy, :create, :edit, :update]

  get '/signup' => 'users#new'
  patch '/documents/:id/update_column', to:'documents#update_column' 
  get '/shared_view', to: 'documents#shared_view'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get "*path", :to => redirect('/')
end

Rapid Share (Without Gems)/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Rapid Share (Without Gems)/app/models/document.rb
require 'json'
class Document < ApplicationRecord

    attr_accessor :uploaded_file
    
    belongs_to :user

    before_validation :set_params
    after_save :upload
    after_destroy :delete_document
  
    validates :description, :presence => true
    validates :name, :presence => true
    validates :path, :presence => true, :uniqueness =>true
    validates :user_id, :presence => true
  

    def set_params
      return false if self.path.nil?
    
      path = JSON.parse(self.path, symbolize_names: true)
      
      hash = DateTime.now.strftime("%Q")
      hashed_name = "#{hash}_#{path[:original_filename]}"
      uploaded_file = ActionDispatch::Http::UploadedFile.new(
        filename: File.basename(path[:original_filename]),
        type: Mime::Type.lookup_by_extension(File.extname(hashed_name)[1..-1]),
        tempfile: File.new(path[:path])
      )
    
      self.name = uploaded_file.original_filename

      self.uploaded_file = uploaded_file
      
      dir = "./uploaded_documents"
      Dir.mkdir(dir) unless File.exists?(dir)
      self.path = File.join(dir, hashed_name)
    end
    
  
    def upload 
      return false if self.uploaded_file.nil?    
      @document = File.open(self.uploaded_file, "rb")
      File.open(self.path, "wb") do |f| 
        f.write(@document.read); 
        f.rewind; 
      end
      @document.close
    end
    
  
    def delete_document
      File.delete(self.path) if File.exists?(self.path)
    end
end

Rapid Share (Without Gems)/app/models/user.rb
class User < ApplicationRecord
    has_many :documents

    validates :name, :presence => true
    validates :email, :presence => true, :uniqueness => true, :format => { with: URI::MailTo::EMAIL_REGEXP }
    validates :user_name, :presence => true, :uniqueness => true

    attr_accessor :password
    before_save :encrypt_password

    def encrypt_password
        if password.present?
            self.password_digest = BCrypt::Password.create(password)
        end
    end

    def authenticate(entered_password)
        BCrypt::Password.new(password_digest) == entered_password
    end

end

Rapid Share (Without Gems)/app/controllers/application_controller.rb
# ApplicationController
class ApplicationController < ActionController::Base
    protect_from_forgery
    helper_method :current_user
  
    def current_user
       @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def require_user
      redirect_to login_url unless current_user
    end
  
    def redirect_if_signed_in?
      redirect_to root_url if current_user
    end
end

Rapid Share (Without Gems)/app/controllers/documents_controller.rb
# DocumentsController
require "json"
class DocumentsController < ApplicationController

  before_action :require_user, :only => [:new, :index, :destroy, :show, :update]
  
    def index
        @documents = current_user.documents
    end
  
    def new
      @document = Document.new
    end
  
    def create
      description = params[:document][:description]
      temp = params[:document][:doc]

      json_temp = JSON.dump({:original_filename => temp.original_filename, :tempfile => temp.tempfile, :path => temp.path})
      @document = current_user.documents.build(:path => json_temp, :description => description)
      if @document.save
        flash[:notice]="File Uploaded Successfully!"
        redirect_to documents_path
      else
        flash[:notice]="Error uploading files"
        render new_document_path
      end
    end
  
    def show
      if document = Document.find_by_id(params[:id])
        path = document.path
        File.open(path, "r") do |f|
          send_data f.read, :filename => document.name
        end
      else
        flash[:notice]="no such file"
        redirect_to root_url
      end
    end
    
    def update_column
      @document = Document.find(params[:id])
      if @document
        if @document.update_attribute(:shared, params[:column_name]) && @document.user_id == session[:user_id]
          true
        end
      end
    end
  
    def destroy
      @document = Document.find(params[:id])
      if @document
        if @document.user_id == session[:user_id]
          @document.destroy
          flash[:notice] = "File deleted"
        else
          flash[:notice] = "You do not own this file"
        end
      else
        flash[:notice] = "No such file"
      end
      redirect_to root_url
    end
  
  def shared_view
    @documents = current_user.documents
    render 'shared/_shared'
  end

end

Rapid Share (Without Gems)/app/controllers/sessions_controller.rb
# SessionsController
class SessionsController < ApplicationController

  before_action :redirect_if_signed_in?, :only => [:new]

    def new
    end

    def create
      user_name = params[:session][:user_name]
      email = params[:session][:email]
      password = params[:session][:password]
      user = User.find_by_user_name(user_name)
      if user && user.authenticate(password)
        session[:user_id] = user.id
        redirect_to root_url
      else
        flash[:notice] = "Incorrect Credentials"
        redirect_to login_url
      end
    end

  def destroy
    session[:user_id]=nil
    redirect_to root_url
  end
  
end

Rapid Share (Without Gems)/app/controllers/users_controller.rb
# UsersController
class UsersController < ApplicationController

  before_action :redirect_if_signed_in?, :only => [:new]  

    def new
      @user = User.new
    end
  
    def create
      name = params[:user][:name]
      email = params[:user][:email]
      password = params[:user][:password]
      user_name = params[:user][:user_name]
      @user = User.new({:name => name, :email => email, :password => password, :user_name => user_name})
      if @user.save
        session[:user_id] = @user.id
        flash[:notice]="Sucessfully signed up..."
        redirect_to root_url
      else
        flash[:notice] = "Error signing up"
        render "new", status: :unprocessable_entity
      end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id]) # Find the user to update
      if @user.update(user_params) # Update the user's attributes
        flash[:notice]= "Successfully updated"
        redirect_to @user
      else
        flash[:notice]= "Error while updating"
        render :edit
      end
    end
    def user_params
      params.require(:user).permit(:name, :email)
    end

end
  

Rapid Share (Without Gems)/app/helpers/application_helper.rb
module ApplicationHelper
end

Rapid Share (Without Gems)/app/helpers/documents_helper.rb
module DocumentsHelper
end

Rapid Share (Without Gems)/app/helpers/sessions_helper.rb
module SessionsHelper
end

Rapid Share (Without Gems)/app/helpers/users_helper.rb
module UsersHelper
    def sign_in(user)
        session[:user_id] = user.id
      end
    
      def sign_out
        session[:user_id] = nil
      end
end

Rapid Share (Without Gems)/app/views/documents/index.html.erb
<script type="text/javascript">
$(document).ready(function() {
  $('.item-checkbox').change(function() {
    var itemId = $(this).val();
    var isChecked = $(this).is(':checked');
    // // Enable/disable the corresponding button based on checkbox state
    if(isChecked) {
      $(`#delete_${itemId}`).attr('class','btn btn-danger ml-3 disabled');
      $(`#download_${itemId}`).attr('class','btn btn-success ml-3');
    }else{
      $(`#delete_${itemId}`).attr('class','btn btn-danger ml-3');
      $(`#download_${itemId}`).attr('class','btn btn-success ml-3 disabled');
    }
    let documentId = document.getElementById(`copy_${itemId}`).getAttribute('value').split('/')[2]
    $.ajax({
    type: 'PATCH',
    url: '/documents/' + documentId + '/update_column',
    data: { column_name: isChecked ? true : false }
  });
  });
});
function copyToClipboard(id) {
  let checkbox = $(`#checkbox_${id}`);
  if (checkbox.prop('checked')) {
    let value = $(`#copy_${id}`).attr('value');
    let url = window.location.host + "/" + value;
    navigator.clipboard.writeText(url);
  }
}

</script>

<title>Documents</title>
<head>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
</head>
<div id="container">
  <div id="docs" style="margin: 20px">
<table class="table table-bordered">
  <thead>
  <tr>
    <th scope="col">Documents</th>
    <th scope="col">Upload Date</th>
    <th scope="col">Description</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
<tbody>
    <% @documents.each_with_index do |document, index| %>
      <tr scope="row">
    <td><%= document.name %></td>
    <td><p class="upload_date"><%= (document.created_at).strftime('%B %d %Y') %></p></td>
    <td><p class="description"><%= document.description %></p></td>
    <td>
      <%= link_to 'Delete', document_path(document), method: :delete, class: "btn btn-danger ml-3", id: "delete_#{index+1}" %>
      <%= link_to 'Download', document_path(document), class: "btn btn-success ml-3 disabled", id: "download_#{index+1}"%> 
      <%= link_to 'Copy',"#" ,id: "copy_#{index+1}", value: document_path(document) ,class: "bi bi-clipboard-minus", :onclick => "return copyToClipboard(#{index+1})"%>
      Share: <%= check_box_tag("checkbox_#{index+1}", "#{index+1}" ,document.shared, class: "item-checkbox") %>
    </td>
  </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

Rapid Share (Without Gems)/app/views/documents/new.html.erb
<script type="text/javascript">
  validateform = function(){
    var description = document.forms["myform"]["description"].value;
    var doc = document.forms["myform"]["doc"].value;
    if(!description){
      alert("description missing");
      return false;
    }
    if(!doc){
      alert("document missing");
      return false;
    }
    return true;
  }
</script>
<%if @document.errors%>
  <div id = "errors">
    <%@document.errors.full_messages.each do |error|%>
      <p>
        <%=error%>
      </p>
    <%end%>
  </div>
<%end%>
<%= form_for @document,:action => :upload, class: "form-group" ,:multipart => true, :id => "myform" do |f|%>
  <p>
    <%= f.label "document" %>
    <%= f.file_field :doc, class:"form-control mb-2" %><br/>
    <%= f.label "description" %>
    <%= f.text_field :description, class:"form-control mx-sm-3 mb-2" %>
  </p>
  <p>
    <%= f.submit "Upload", :onclick => "return validateform();", class: "btn btn-primary ml-3" %>
  </p>
  
<% end %>

Rapid Share (Without Gems)/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RapidShare</title>
  <%# <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag %>
  <%= csrf_meta_tag %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<!-- Option 1: Include in HTML -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <%= javascript_importmap_tags %>
</head>
<body>
  <%= render 'shared/header', locals: {user: @user, current_user: @current_user}%>
  <% if flash.now[:notice] %>
    <div id="notice" style="background-color:red"><%= flash[:notice] %></div>
    <script type="text/javascript">
      var notice = document.getElementById("notice");
      notice.style.opacity=1;
      var interval = setInterval(function(){
        notice.style.opacity-=0.01;
      },100);
      setTimeout(function(){
        clearInterval(interval);
        notice.remove();
      },5000);
    </script>
    <%flash[:notice]=nil%>
  <% end %>
  <div class="nav">
    <% if current_user %>
      <ul>
        <li><%= link_to 'View Shared Documents', shared_view_url,locals: { documents: @documents } %></li>
        <li><%= link_to "Add Document", new_document_path %></li>
      </ul>

    <% end %>
  </div>
<%= yield %>

</body>
</html>

Rapid Share (Without Gems)/app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<div class="container-md">
<%= link_to 'RapidShare', root_path, class:'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  </button>
    <div class="navbar-text">
        <% if current_user %>
            <%= link_to "#{current_user.name}", edit_user_path(current_user)%> &nbsp;
            <%= link_to "Log out", logout_url %>
        <% end %>
    </div>
  </div>

</nav>

Rapid Share (Without Gems)/app/views/shared/_shared.html.erb
<script type="text/javascript">
$(document).ready(function() {
  $('.item-checkbox').change(function() {
    var itemId = $(this).val();
    var isChecked = $(this).is(':checked');
    // // Enable/disable the corresponding button based on checkbox state
    if(isChecked) {
      $(`#delete_${itemId}`).attr('class','btn btn-danger ml-3 disabled');
      $(`#download_${itemId}`).attr('class','btn btn-success ml-3');
    }else{
      $(`#delete_${itemId}`).attr('class','btn btn-danger ml-3');
      $(`#download_${itemId}`).attr('class','btn btn-success ml-3 disabled');
    }
    let documentId = document.getElementById(`copy_${itemId}`).getAttribute('value').split('/')[2]
    $.ajax({
    type: 'PATCH',
    url: '/documents/' + documentId + '/update_column',
    data: { column_name: isChecked ? true : false }
  });
  });
});

  function copytoclipboard(id) {
      let checkbox = document.getElementById(`checkbox_${id}`)
      if(checkbox.checked){
        let value = document.getElementById(`copy_${id}`).getAttribute('value');
        let url =window.location.host+"/"+value
        navigator.clipboard.writeText(`${url}`)
      }
  }
</script>

<title>Shared Documents</title>
<head>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
</head>
<div id="container">
  <div id="docs" style="margin: 20px">
<table class="table table-bordered">
  <thead>
  <tr>
    <th scope="col">Documents</th>
    <th scope="col">Description</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>
<tbody>
    <% @documents.each_with_index do |document, index| %>
    <% if document.shared %>
      <tr scope="row">
    <td><%= document.name %></td>
    <td><p class="description"><%= document.description %></p></td>
    <td>
      <%= link_to 'Download', document_path(document), class: "btn btn-success ml-3", id: "download_#{index+1}"%> 
    </td>
  </tr>
  <% end%>
    <% end %>
  </tbody>
</table>
  </div>
</div>

Rapid Share (Without Gems)/app/views/users/edit.html.erb
<div>

<p>Edit Profile</p>

<%= form_with model: @user, url: user_path(@user), method: :patch ,class: "form-group" , id: "updateform" do |f| %>
  <p>
    <%= f.label "User Name" %>
    <%= f.text_field :user_name, class:"form-control mb-2", :readonly => true%><br/>    
    <%= f.label "Name" %>
    <%= f.text_field :name, class:"form-control mb-2" %><br/>
    <%= f.label "Email" %>
    <%= f.text_field :email, class:"form-control mx-sm-3 mb-2" %>
  </p>
  <p>
    <%= f.submit "Update", class: "btn btn-primary ml-3" %>
  </p>

<% end %>

</div>

Rapid Share (Without Gems)/app/views/users/new.html.erb
<script>
  $(document).ready(function() {

    $('#password').on("input", function() {
      // event.preventDefault();
      var password = this.value;
      var errors = [];

      // Password length validation
      if (password.length <= 8) {
        errors.push('Password must be greater than 8 characters.');
        $('#submit_button').attr('class', "btn btn-primary ml-3 disabled")
      }

      // Uppercase letter validation
      if (!/[A-Z]/.test(password)) {
        errors.push('Password must include at least one uppercase letter.');
      }

      // Lowercase letter validation
      if (!/[a-z]/.test(password)) {
        errors.push('Password must include at least one lowercase letter.');
      }

      // Number validation
      if (!/[0-9]/.test(password)) {
        errors.push('Password must include at least one number.');
      }

      // Display errors
      if (errors.length > 0) {
        var errorHtml = '';
        $.each(errors, function(index, error) {
          errorHtml += '<p>' + error + '</p>';
        });
        $('#password-errors').html(errorHtml);
      } else {
        // Submit the form if validation passes
        var errorHtml = '';
        $('#password-errors').html(errorHtml);
        $('#submit_button').attr('class', "btn btn-primary ml-3");
      }
    });
  });
</script>

<%if @user.errors%>
  <div id = "errors">
    <%@user.errors.full_messages.each do |error|%>
      <p>
        <%=error%>
      </p>
    <%end%>
  </div>
<%end%>
<div class="signup">
  <div class="container">
    <br>
    <br>

    <%= form_for @user,  class: "form-group", id: "signup_form" , :method => "post" do |f| %>
      <div><%= f.text_field :user_name, class:"form-control mb-2", :placeholder => 'User Name' %></div>
      <div><%= f.text_field :name, class:"form-control mb-2", :placeholder => 'Name' %></div>
      <div><%= f.email_field :email, class:"form-control mb-2", :placeholder => 'Email' %></div>
      <div><%= f.password_field :password, id: "password" ,class:"form-control mb-2", :placeholder => 'Password' %></div>
      <div><%= f.submit "Signup", class: "btn btn-primary ml-3 disabled", id: "submit_button" %></div>
      <div id="password-errors"></div>
    <% end %>
  </div>
</div>